name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --upgrade pip -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Build deployment package
        run: zip -r kesavan_share_app.zip .

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1  # Change to your desired region

      - name: Upload to S3
        run: |
          aws s3 cp kesavan_share_app.zip s3://k7-lambda-bucket1/kesavan_share_app.zip

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name share-app-v1-lambda --s3-bucket k7-lambda-bucket1 --s3-key kesavan_share_app.zip
