name: Deploy to AWS lambda

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/checkout@v2
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: build
        run: zip -r kesavan_share_app.zip

      - name: AWS deploy
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired region
          function-name: share-app-v1-lambda # Change to your Lambda function name
          zip-file: kesavan_share_app.zip



